Repository estsoft/estsoft.github.io, pull requests merged in 2022-09, with the labels that each got.

#14 fix: readtime 변경 & author 추가
  _includes/header.html
  _posts/2019-10-30-블로그-소개-및-운영원칙.md
  _posts/2019-11-01-시계열-분석과-페어트레이딩-part-1.md
  _posts/2019-11-02-task-oriented-dialog-systems-meet-bert.md
  _posts/2019-11-03-셀럽-now-딥러닝-기반의-연예-뉴스-분석-시스템.md
  _posts/2019-11-04-안경-검색-서비스-glasses-finder.md
  _posts/2019-11-05-ai-plus-2019-컨퍼런스-소개.md
  _posts/2019-12-05-시계열-분석과-페어트레이딩-part-2.md
  _posts/2020-01-05-ai-rd-그랜드-챌린지-상황인지-트랙-2위-줌인터넷.md
  _posts/2020-01-20-ai-앱-개발을-위한-학습용-데이터-구축기.md
  _posts/2020-02-05-메트릭러닝-기반-안경-검색-서비스-개발기2.md
  _posts/2020-03-06-딥러닝-모델-압축-방법론과-bert-압축.md
  _posts/2020-04-06-행위-기반-악성코드-검색-시스템-개발-후기.md
  _posts/2020-05-06-neurips-2019-논문-통계.md
  _posts/2020-06-08-iclr-2020-논문-발표.md
  _posts/2020-07-06-문서-이해-ai-연구-동향.md
  _posts/2020-07-29-공지.md
  _posts/2020-08-06-2020-인공지능-온라인-경진대회-참가기.md
  _posts/2020-09-07-icml-2020-발표-논문.md
  _posts/2020-09-25-aiplus2020.md
  _posts/2020-10-05-100-ai.md
  _posts/2020-10-06-ner.md
  _posts/2020-10-16-aiplus2020-컨퍼런스-현장.md
  _posts/2020-11-09-ssl.md
  _posts/2020-12-07-ai-anchor.md
  _posts/2021-01-06-2020-ai-challenge.md
  _posts/2021-02-08-fake-news.md
  _posts/2021-03-08-employment-rate.md
  _posts/2021-04-06-employment-rate-2.md
  _posts/2021-05-06-bayesian-optimization-in-trading.md
  _posts/2021-06-07-news-summary.md
  _posts/2021-09-02-딥러닝-생성모델과-잠재-벡터에-관하여.md
  _posts/2021-12-08-2021aicontest.md
  _posts/2022-02-15-생성-모델의-새로운-흐름-확산-모델diffusion-model에-관하여.md
  _posts/2022-06-10-인공지능-음성-생성-연구-음성-분류-솔루션.md
  make-template.sh
Labels: bug-fix

#15 main style 수정
  Gemfile
  _config.yml
  _layouts/base.html
  _layouts/home.html
  assets/css/beautifuljekyll.css
Labels: feature

#18 404 page
  404.html
  assets/css/beautifuljekyll.css
  assets/img/logo.png
  assets/img/logo_estsoft_tech.png
Labels: feature

#17 sub, footer 수정
  _includes/footer.html
  assets/css/beautifuljekyll.css
  assets/img/img_footer_logo.png
  assets/img/spr_footer_sns.png
Labels: feature

#16 main search 수정
  _includes/search.html
  assets/css/beautifuljekyll.css
  assets/img/btn_search_close.png
Labels: feature

#19 메인으로 이동 링크 추가
  404.html
Labels: bug-fix

#21 ios 버그 수정
  assets/css/beautifuljekyll.css
Labels: bug-fix

#22 Develop
  assets/css/beautifuljekyll.css
Labels: bug-fix

#23 ios ellipsis 안먹는 버그 다시 수정
  assets/css/beautifuljekyll.css
Labels: bug-fix

#24 Develop
  assets/css/beautifuljekyll.css
Labels: bug-fix

#25 로고 변경, 전체 폰트 수정, 리스트 마우스오버시 컬러 추가, 본문 하단 공유하기 버튼 추가, 전체 하단 페이지 버튼 여백 추가
  _config.yml
  _layouts/base.html
  _layouts/post.html
  _posts/2019-11-01-시계열-분석과-페어트레이딩-part-1.md
  _posts/2021-01-06-2020-ai-challenge.md
  _posts/2021-12-08-2021aicontest.md
  assets/css/beautifuljekyll.css
  assets/img/btn_search.png
  assets/img/img_share.png
  assets/img/logo.png
Labels: bug-fix, feature

#26 fix: 티스토리 아이콘 삭제
  _config.yml
  _includes/footer.html
  _layouts/base.html
  _layouts/post.html
  _posts/2019-11-01-시계열-분석과-페어트레이딩-part-1.md
  _posts/2021-01-06-2020-ai-challenge.md
  _posts/2021-12-08-2021aicontest.md
  assets/css/beautifuljekyll.css
  assets/img/btn_search.png
  assets/img/img_share.png
  assets/img/logo.png
Labels: bug-fix
